version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./www:/var/www/html

  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    build:
      context: ./docker/redis
    volumes:
      - ./docker/redis/data:/data
    ports:
        - 6379:6379